# Credits

This is heavily influenced or copied from https://github.com/pytorch/tutorials

# What is PyTorch?

> **NOTE** In the last part of this lab cuda is used. If you have a cuda enabled machine, read the README.md in the root of this repo on how to use nvidia-docker.


It’s a Python based scientific computing package targeted at two sets of
audiences:
-  A replacement for numpy to use the power of GPUs
-  a deep learning research platform that provides maximum flexibility
   and speed


# Getting Started

In this lab you will get a quick start on what pytorch is and how to use it.

## 1. Tensors

Tensors are similar to numpy’s ndarrays, with the addition being that
Tensors can also be used on a GPU to accelerate computing.

In [1]:
import torch

Construct a 5x3 matrix, uninitialized

In [2]:
x = torch.Tensor(5, 3)
print(x)

tensor([[-2.3927e-12,  4.5595e-41,  1.4433e-38],
        [ 0.0000e+00, -4.3204e-36, -7.6520e+18],
        [-2.4162e-12,  4.5595e-41,  1.4344e-38],
        [ 0.0000e+00, -3.0630e-30,  1.6413e-35],
        [-2.4163e-12,  4.5595e-41,  1.4339e-38]])


Construct a randomly initialized matrix

In [3]:
x = torch.rand(5, 3)
print(x)

tensor([[0.8025, 0.3373, 0.9409],
        [0.3122, 0.8728, 0.2662],
        [0.6201, 0.8995, 0.2167],
        [0.9781, 0.2614, 0.8049],
        [0.6472, 0.6178, 0.8476]])


Get its size

In [4]:
print(x.size())

torch.Size([5, 3])


**NOTE** `torch.Size` is in fact a tuple, so it supports the same operations

In [5]:
x[1:3] = 2
print(x)

tensor([[0.8025, 0.3373, 0.9409],
        [2.0000, 2.0000, 2.0000],
        [2.0000, 2.0000, 2.0000],
        [0.9781, 0.2614, 0.8049],
        [0.6472, 0.6178, 0.8476]])


# Assignment

Make use of the pytorch docs <http://pytorch.org/docs/torch>
1. Make a tensor of size (2, 17)
2. Make a torch.FloatTensor of size (3, 1)
3. Make a torch.LongTensor of size (5, 2, 1)
  - fill the entire tensor with 7s
4. Make a torch.ByteTensor of size (5,)
  - fill the middle 3 indices with ones such that it records [0, 1, 1, 1, 0]

In [21]:
# 1)
print('\n1)')
y = torch.Tensor(2,17)
print(y.size())

# 2)
print('\n2)')
y = torch.FloatTensor(3,1)
print(y.size())
print(y.dtype)

# 3)
print('\n3)')
y = torch.LongTensor(5,2,1)
y[:] = 7
print(y)
print(y.dtype)

print('\n4)')
y = torch.ByteTensor(5,)
y[:] = 0
y[1:4] = 1
print(y)
print(y.dtype)



1)
torch.Size([2, 17])

2)
torch.Size([3, 1])
torch.float32

3)
tensor([[[7],
         [7]],

        [[7],
         [7]],

        [[7],
         [7]],

        [[7],
         [7]],

        [[7],
         [7]]])
torch.int64

4)
tensor([0, 1, 1, 1, 0], dtype=torch.uint8)
torch.uint8


## 2. Operations
There are multiple syntaxes for operations. Let's see addition as an example:

### 2.1 Addition: syntax 1

In [22]:
y = torch.rand(5, 3)
print(x + y)

tensor([[1.3776, 0.5578, 1.3252],
        [2.9496, 2.5630, 2.1253],
        [2.6614, 2.5251, 2.6845],
        [1.6296, 0.7323, 1.6916],
        [1.3102, 0.8512, 1.7207]])


### 2.2 Addition: syntax 2

In [23]:
print(torch.add(x, y))

tensor([[1.3776, 0.5578, 1.3252],
        [2.9496, 2.5630, 2.1253],
        [2.6614, 2.5251, 2.6845],
        [1.6296, 0.7323, 1.6916],
        [1.3102, 0.8512, 1.7207]])


### 2.3 Addition: giving an output tensor

In [24]:
result = torch.Tensor(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[1.3776, 0.5578, 1.3252],
        [2.9496, 2.5630, 2.1253],
        [2.6614, 2.5251, 2.6845],
        [1.6296, 0.7323, 1.6916],
        [1.3102, 0.8512, 1.7207]])


### 2.4 Addition: in-place

adds `x`to `y`

In [25]:
y.add_(x)
print(y)

tensor([[1.3776, 0.5578, 1.3252],
        [2.9496, 2.5630, 2.1253],
        [2.6614, 2.5251, 2.6845],
        [1.6296, 0.7323, 1.6916],
        [1.3102, 0.8512, 1.7207]])


**NOTE** Any operation that mutates a tensor in-place is post-fixed with an `_`. For example: `x.copy_(y)`, `x.t_()`, will change `x`.

You can use standard numpy-like indexing with all bells and whistles!

In [26]:
print(x[:, 1])

tensor([0.3373, 2.0000, 2.0000, 0.2614, 0.6178])


**Read later** 100+ Tensor operations, including transposing, indexing, slicing, mathematical operations, linear algebra, random numbers, etc are described here <http://pytorch.org/docs/torch>

# Assignment

1. multiply of two tensors (see [torch.Tensor.mul](http://pytorch.org/docs/master/tensors.html#torch.Tensor.mul))
2. do the same, but inplace
3. division of two tensors (see [torch.Tensor.div](http://pytorch.org/docs/master/tensors.html#torch.Tensor.div))
4. perform a matrix multiplication of two tensors of size (2, 4) and (4, 2)

In [32]:
# 1)
print('\n1)')
print(x*y)

# 2)
print('\n2)')
print(y.mul_(x))

# 3)
print('\n3)')
print(y / x)

# 4)
print('\n4)')
print(torch.matmul(torch.rand(2,4), torch.rand(4,2)))


1)
tensor([[5.7146e-01, 7.2175e-03, 1.0386e+00],
        [4.7193e+01, 4.1007e+01, 3.4004e+01],
        [4.2582e+01, 4.0402e+01, 4.2952e+01],
        [1.4917e+00, 3.4207e-03, 7.1010e-01],
        [2.2987e-01, 1.2401e-01, 8.8823e-01]])

2)
tensor([[5.7146e-01, 7.2175e-03, 1.0386e+00],
        [4.7193e+01, 4.1007e+01, 3.4004e+01],
        [4.2582e+01, 4.0402e+01, 4.2952e+01],
        [1.4917e+00, 3.4207e-03, 7.1010e-01],
        [2.2987e-01, 1.2401e-01, 8.8823e-01]])

3)
tensor([[7.1207e-01, 2.1400e-02, 1.1038e+00],
        [2.3596e+01, 2.0504e+01, 1.7002e+01],
        [2.1291e+01, 2.0201e+01, 2.1476e+01],
        [1.5250e+00, 1.3085e-02, 8.8220e-01],
        [3.5518e-01, 2.0073e-01, 1.0479e+00]])

4)
tensor([[0.3430, 0.3599],
        [0.7336, 0.7940]])


## 3. Numpy Bridge

Converting a torch Tensor to a numpy array and vice versa is a breeze.

The torch Tensor and numpy array will share their underlying memory locations, and changing one will change the other.

### 3.1 Converting torch Tensor to numpy Array

In [33]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [34]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


See how the numpy array changed in value.

In [35]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


### 3.2 Converting numpy Array to torch Tensor

See how changing the np array changed the torch Tensor automatically

In [36]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


# Assignment

1. create a tensor of size (5, 2) containing ones
2. now convert it to a numpy array
3. now convert it back to a torch tensor

In [39]:
# 1)
print('\n1)')
y = torch.ones(5,2)
print(y)

# 2)
print('\n2)')
y_np = y.numpy()
print(y_np)

# 3)
print('\n3)')
y_torch = torch.from_numpy(y_np)
print(y_torch)


1)
tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])

2)
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

3)
tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])


All the Tensors on the CPU except a CharTensor support converting to NumPy and back.

## 4 CUDA Tensors

Tensors can be moved onto GPU using the `.cuda` function.
This is not necessary, but check the `README.md` for details on how to use a GPU with docker.

In [40]:
# let us run this cell only if CUDA is available
if torch.cuda.is_available():
    x = x.cuda()
    y = y.cuda()
    z = x + y
    # notice that the tensors are now of type torch.cuda.FloatTensor (notice the cuda in there)
    # this is meant as a tensor to be run on the GPU.
    # the .cuda() does this to any parameter it is applied to
    print(x)
    print(y)
    print(z)
else:
    print("CUDA not available on your machine.")

CUDA not available on your machine.
